version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./infrastructure/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shop.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongodb:
    image: mongo:7
    volumes:
      - ./infrastructure/mongodb/data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./services/user-service
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shop_user
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  auth-service:
    build: ./services/auth-service
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shop_auth
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  product-service:
    build: ./services/product-service
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/shop_products
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  order-service:
    build: ./services/order-service
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shop_order
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  payment-service:
    build: ./services/payment-service
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shop_payment
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  inventory-service:
    build: ./services/inventory-service
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=shop_inventory
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  cart-service:
    build: ./services/cart-service
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/shop_cart
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

  notification-service:
    build: ./services/notification-service
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq
      - QUEUE_NAME=notifications
    depends_on:
      - rabbitmq
    ports:
      - "0:3000"

